blank_issues_enabled: false
contact_links:
  - name: Canaan Official Website
    about: Canaan 官方网站
    url: https://www.canaan-creative.com/
  - name: Kendryte Community
    about: Kendryte 开发者社区
    url: https://developer.canaan-creative.com/
