#define MICROPY_HW_BOARD_NAME               "K230d_canmv"
#define MICROPY_HW_MCU_NAME                 "k230d"
#define OMV_ARCH_STR                        "K230"
#define OMV_BOARD_TYPE                      "CanMV"
#define MICROPY_BANNER_MACHINE MICROPY_HW_BOARD_NAME " with " "only_rtt_" "_outbuf4"
