# $(XUANTIE)g++ -c kpu.cpp -I../include/kpu -I../include/kpu/riscv64/nncase/include/ -I../include/kpu/riscv64 -I../include/kpu/riscv64/nncase/include/nncase/runtime -L../include/riscv64/nncase/lib -std=c++20
XUANTIE = ../../k230_sdk/toolchain/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin/riscv64-unknown-linux-musl-


CPP_SRC = $(wildcard *.cpp)

C_SRC = $(wildcard *.c)

CPP_OBJ = $(CPP_SRC:.cpp=.o)

C_OBJ = $(C_SRC:.c=.o)

EXEC = main

INC = -I../include/kpu \
-I../include/kpu/riscv64 \
-I../include/kpu/riscv64/nncase/include/ \
-I../include/kpu/riscv64/nncase/include/nncase/runtime \
-L../include/riscv64/nncase/lib \

MC_INC= -I../../k230_sdk/toolchain/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/riscv64-unknown-linux-musl/include/c++/12.0.1 \
-I../../k230_sdk/toolchain/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/riscv64-unknown-linux-musl/include/c++/12.0.1/riscv64-unknown-linux-musl \
-I../../micropython \
-I../include/core \
-I../../micropython/mpy-cross \
-I../../output/k230_evb_defconfig/micropython/

CXXFLAGS = $(INC) -std=c++20

CFLAGS = $(INC) $(MC_INC)


.PHONY: all
all: nncase_wrap.o kpu.o modkpu.o kpu.mpy

nncase_wrap.o: nncase_wrap.cpp 
	$(XUANTIE)g++ -c -o $@ $< $(CXXFLAGS) -fno-delete-null-pointer-checks

kpu.o: kpu.c nncase_wrap.o
	$(XUANTIE)gcc -c -o $@ $< $(CFLAGS) -fPIC

modkpu.o: modkpu.c nncase_wrap.o kpu.o
	$(XUANTIE)gcc -c -o $@ $< $(CFLAGS) -fPIC
	
kpu.mpy: modkpu.o kpu.o
	$(XUANTIE)gcc -o $@ $^ $(CFLAGS) -shared -fPIC
	
# $(EXEC): $(CPP_OBJ) $(C_OBJ)
# 	$(XUANTIE)g++ -o $@ $^ -lstdc++ -lm -libc


clean: 
	rm -f $(EXEC) $(CPP_OBJ) $(C_OBJ) kpu.mpy